services:
  dbservice:
    image: dbservice
    restart: unless-stopped
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN
      - NGROK_DOMAIN
    command: http --domain $NGROK_DOMAIN http://dbservice:3000
